<template>
  <div>
    <div class="leui-picker-new-container-column" ref="column">
        <div class="leui-picker-new-container-row" v-for="(item, index) in values" :key="index" :style="{height:`${itemHeight}px`}">
          {{item.label || item }}
        </div>
      </div>
  </div>
</template>
<script>
export default{
 data(){
    return {
      values: [{
        label: '哈哈哈',
        value: 'hh'
      }, {
        label: '哈哈哈1',
        value: 'hh1'
      }, {
        label: '哈哈哈2',
        value: 'hh2'
      }, {
        label: '哈哈哈1',
        value: 'hh3'
      }, {
        label: '哈哈哈2',
        value: 'hh4'
      }, {
        label: '哈哈哈1',
        value: 'hh5'
      }, {
        label: '哈哈哈2',
        value: 'hh2'
      }, {
        label: '哈哈哈1',
        value: 'hh3'
      }, {
        label: '哈哈哈2',
        value: 'hh4'
      }, {
        label: '哈哈哈1',
        value: 'hh5'
      }, {
        label: '哈哈哈2',
        value: 'hh2'
      }, {
        label: '哈哈哈1',
        value: 'hh3'
      }, {
        label: '哈哈哈2',
        value: 'hh4'
      }, {
        label: '哈哈哈1',
        value: 'hh5'
      }, {
        label: '哈哈哈2',
        value: 'hh2'
      }, {
        label: '哈哈哈1',
        value: 'hh3'
      }, {
        label: '哈哈哈2',
        value: 'hh4'
      }, {
        label: '哈哈哈1',
        value: 'hh5'
      }, {
        label: '哈哈哈2',
        value: 'hh2'
      }, {
        label: '哈哈哈1',
        value: 'hh3'
      }, {
        label: '哈哈哈2',
        value: 'hh4'
      }, {
        label: '哈哈哈1',
        value: 'hh5'
      }, {
        label: '哈哈哈2',
        value: 'hh2'
      }, {
        label: '哈哈哈1',
        value: 'hh3'
      }, {
        label: '哈哈哈2',
        value: 'hh4'
      }, {
        label: '哈哈哈1',
        value: 'hh5'
      }, {
        label: '哈哈哈2',
        value: 'hh2'
      }, {
        label: '哈哈哈1',
        value: 'hh3'
      }, {
        label: '哈哈哈2',
        value: 'hh4'
      }, {
        label: '哈哈哈1',
        value: 'hh5'
      }, {
        label: '哈哈哈2',
        value: 'hh2'
      }, {
        label: '哈哈哈1',
        value: 'hh3'
      }, {
        label: '哈哈哈2',
        value: 'hh4'
      }, {
        label: '哈哈哈1',
        value: 'hh5'
      }, {
        label: '哈哈哈2',
        value: 'hh2'
      }, {
        label: '哈哈哈1',
        value: 'hh3'
      }, {
        label: '哈哈哈2',
        value: 'hh4'
      }, {
        label: '哈哈哈1',
        value: 'hh5'
      }, {
        label: '哈哈哈2',
        value: 'hh2'
      }, {
        label: '哈哈哈1',
        value: 'hh3'
      }, {
        label: '哈哈哈2',
        value: 'hh4'
      }, {
        label: '哈哈哈1',
        value: 'hh5'
      }, {
        label: '哈哈哈2',
        value: 'hh2'
      }, {
        label: '哈哈哈1',
        value: 'hh3'
      }, {
        label: '哈哈哈2',
        value: 'hh4'
      }, {
        label: '哈哈哈1',
        value: 'hh5'
      }, {
        label: '哈哈哈2',
        value: 'hh2'
      }, {
        label: '哈哈哈1',
        value: 'hh3'
      }, {
        label: '哈哈哈2',
        value: 'hh4'
      }, {
        label: '哈哈哈1',
        value: 'hh5'
      }, {
        label: '哈哈哈2',
        value: 'hh2'
      }, {
        label: '哈哈哈1',
        value: 'hh3'
      }, {
        label: '哈哈哈2',
        value: 'hh4'
      }, {
        label: '哈哈哈1',
        value: 'hh5'
      }, {
        label: '哈哈哈2',
        value: 'hh2'
      }, {
        label: '哈哈哈1',
        value: 'hh3'
      }, {
        label: '哈哈哈2',
        value: 'hh4'
      }, {
        label: '哈哈哈1',
        value: 'hh5'
      }, {
        label: '哈哈哈2',
        value: 'hh2'
      }, {
        label: '哈哈哈1',
        value: 'hh3'
      }, {
        label: '哈哈哈2',
        value: 'hh4'
      }, {
        label: '哈哈哈1',
        value: 'hh5'
      }, {
        label: '哈哈哈2',
        value: 'hh2'
      }, {
        label: '哈哈哈1',
        value: 'hh3'
      }, {
        label: '哈哈哈2',
        value: 'hh4'
      }, {
        label: '哈哈哈1',
        value: 'hh5'
      }, {
        label: '哈哈哈2',
        value: 'hh2'
      }, {
        label: '哈哈哈1',
        value: 'hh3'
      }, {
        label: '哈哈哈2',
        value: 'hh4'
      }, {
        label: '哈哈哈1',
        value: 'hh5'
      }, {
        label: '哈哈哈2',
        value: 'hh2'
      }, {
        label: '哈哈哈1',
        value: 'hh3'
      }, {
        label: '哈哈哈2',
        value: 'hh4'
      }, {
        label: '哈哈哈1',
        value: 'hh5'
      }, {
        label: '哈哈哈2',
        value: 'hh2'
      }, {
        label: '哈哈哈1',
        value: 'hh3'
      }, {
        label: '哈哈哈2',
        value: 'hh4'
      }, {
        label: '哈哈哈1',
        value: 'hh5'
      }, {
        label: '哈哈哈2',
        value: 'hh2'
      }, {
        label: '哈哈哈1',
        value: 'hh3'
      }, {
        label: '哈哈哈2',
        value: 'hh4'
      }, {
        label: '哈哈哈1',
        value: 'hh5'
      }, {
        label: '哈哈哈2',
        value: 'hh2'
      }, {
        label: '哈哈哈1',
        value: 'hh3'
      }, {
        label: '哈哈哈2',
        value: 'hh4'
      }, {
        label: '哈哈哈1',
        value: 'hh5'
      }, {
        label: '哈哈哈2',
        value: 'hh2'
      }, {
        label: '哈哈哈1',
        value: 'hh3'
      }, {
        label: '哈哈哈2',
        value: 'hh4'
      }, {
        label: '哈哈哈1',
        value: 'hh5'
      }, {
        label: '哈哈哈2',
        value: 'hh2'
      }, {
        label: '哈哈哈1',
        value: 'hh3'
      }, {
        label: '哈哈哈2',
        value: 'hh4'
      }, {
        label: '哈哈哈1',
        value: 'hh5'
      }, {
        label: '哈哈哈2',
        value: 'hh2'
      }, {
        label: '哈哈哈1',
        value: 'hh3'
      }, {
        label: '哈哈哈2',
        value: 'hh4'
      }, {
        label: '哈哈哈1',
        value: 'hh5'
      }, {
        label: '哈哈哈2',
        value: 'hh2'
      }, {
        label: '哈哈哈1',
        value: 'hh3'
      }, {
        label: '哈哈哈2',
        value: 'hh4'
      }, {
        label: '哈哈哈1',
        value: 'hh5'
      }, {
        label: '哈哈哈2',
        value: 'hh6'
      }, {
        label: '哈哈哈3',
        value: 'hh7'
      }]
    }
  },
  props: {
    data: Array,
    value: String,
    visibleItemCount: Number,
    itemHeight: Number // 单位px
  },
  created(){

  }
}
</script>
<style lang="less">
.leui-picker-new-container-column{
  height: 100%;
}
.leui-picker-new-container-row{
  
}

</style>